export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const REFETCH_USER_DATA = "REFETCH_USER_DATA";
export const CREATE_USER_LOADING = "CREATE_USER_LOADING";
